export const BOOK_FETCHED = 'BOOK_FETCHED';
export const BOOK_FETCHED_SUCCEEDED = 'BOOK_FETCHED_SUCCEEDED';
export const BOOK_FETCHED_FAILED = 'BOOK_FETCHED_FAILED';

export const ALL_BOOKS_FETCHED = 'ALL_BOOKS_FETCHED';
export const ALL_BOOKS_FETCHED_SUCCEEDED = 'ALL_BOOKS_FETCHED_SUCCEEDED';
export const ALL_BOOKS_FETCHED_FAILED = 'ALL_BOOKS_FETCHED_FAILED';
