export const PLAYLIST_CREATED = 'PLAYLIST_CREATED';
export const PLAYLIST_CREATED_SUCCEEDED = 'PLAYLIST_CREATED_SUCCEEDED';
export const PLAYLIST_CREATED_FAILED = 'PLAYLIST_CREATED_FAILED';

export const PLAYLIST_FETCHED = 'PLAYLIST_FETCHED';
export const PLAYLIST_FETCHED_SUCCEEDED = 'PLAYLIST_FETCHED_SUCCEEDED';
export const PLAYLIST_FETCHED_FAILED = 'PLAYLIST_FETCHED_FAILED';

export const ALL_PLAYLIST_FETCHED = 'ALL_PLAYLIST_FETCHED';
export const ALL_PLAYLIST_FETCHED_SUCCEEDED = 'ALL_PLAYLIST_FETCHED_SUCCEEDED';
export const ALL_PLAYLIST_FETCHED_FAILED = 'ALL_PLAYLIST_FETCHED_FAILED';

export const PLAYLIST_RATED = 'PLAYLIST_RATED';
export const PLAYLIST_RATED_SUCCEEDED = 'PLAYLIST_RATED_SUCCEEDED';
export const PLAYLIST_RATED_FAILED = 'PLAYLIST_RATED_FAILED';

export const PLAYLIST_COMMENTED = 'PLAYLIST_COMMENTED';
export const PLAYLIST_COMMENT_SUCCEEDED = 'PLAYLIST_COMMENTED_SUCCEEDED';
export const PLAYLIST_COMMENT_FAILED = 'PLAYLIST_COMMENT_FAILED';