export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_REGISTERED_SUCCEEDED = 'USER_REGISTERED_SUCCEEDED';
export const USER_REGISTERED_FAILED = 'USER_REGISTERED_FAILED';

export const USER_LOGGED= 'USER_LOGGED';
export const USER_LOGGED_SUCCEEDED = 'USER_LOGGED_SUCCEEDED';
export const USER_LOGGED_FAILED = 'USER_LOGGED_FAILED';

export const USER_FETCHED= 'USER_FETCHED';
export const USER_FETCHED_SUCCEEDED = 'USER_FETCHED_SUCCEEDED';
export const USER_FETCHED_FAILED = 'USER_FETCHED_FAILED';

export const ALL_USERS_FETCHED= 'ALL_USERS_FETCHED';
export const ALL_USERS_FETCHED_SUCCEEDED = 'ALL_USERS_FETCHED_SUCCEEDED';
export const ALL_USERS_FETCHED_FAILED = 'ALL_USERS_FETCHED_FAILED';